services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=cinema_manager'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=admin'
    ports:
      - '3306'
